#!/bin/bash
# Bulk compliance check across all environments

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ANSIBLE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
TIMESTAMP=$(date +%Y%m%d-%H%M%S)
REPORT_DIR="$ANSIBLE_DIR/compliance-reports/$TIMESTAMP"

echo "========================================"
echo "Bulk Compliance Check"
echo "========================================"
echo ""

mkdir -p "$REPORT_DIR"
cd "$ANSIBLE_DIR"

# Scan all environments
for env in production staging test; do
  echo "Scanning $env environment..."

  ansible-playbook -i inventory.ini run-quantum-sniffer.yml \
    -l "$env" \
    -e "scan_ports=22,443,3389" \
    -f 10 \
    2>&1 | tee "$REPORT_DIR/$env-scan.log"

  echo ""
done

# Generate compliance report
echo "Generating compliance report..."
echo ""

cat > "$REPORT_DIR/compliance-report.md" <<EOF
# Quantum Cryptography Compliance Report
**Date:** $(date)
**Scope:** All environments (production, staging, test)

## Summary

EOF

# Count results
total=0
pq_capable=0
classical=0

for json_file in "$ANSIBLE_DIR/results"/*.json; do
  if [ -f "$json_file" ]; then
    total=$((total + 1))

    # Check PQ status
    pq_status=$(jq -r '.results[0].post_quantum_secure // "Unknown"' "$json_file")

    if [ "$pq_status" = "Yes" ] || [ "$pq_status" = "Hybrid" ]; then
      pq_capable=$((pq_capable + 1))
    elif [ "$pq_status" = "No" ]; then
      classical=$((classical + 1))
    fi
  fi
done

if [ $total -gt 0 ]; then
  pq_pct=$(awk "BEGIN {printf \"%.1f\", ($pq_capable/$total)*100}")
  classical_pct=$(awk "BEGIN {printf \"%.1f\", ($classical/$total)*100}")
else
  pq_pct="0.0"
  classical_pct="0.0"
fi

cat >> "$REPORT_DIR/compliance-report.md" <<EOF
- **Total Hosts Scanned:** $total
- **PQ-Capable:** $pq_capable ($pq_pct%)
- **Classical Only:** $classical ($classical_pct%)
- **Compliance Rate:** $pq_pct%

## Hosts by Status

### PQ-Capable Hosts (Yes/Hybrid)

EOF

# List PQ-capable hosts
for json_file in "$ANSIBLE_DIR/results"/*.json; do
  if [ -f "$json_file" ]; then
    hostname=$(basename "$json_file" | cut -d'-' -f1)
    pq_status=$(jq -r '.results[0].post_quantum_secure // "Unknown"' "$json_file")
    ip=$(jq -r '.results[0].target_ip // "N/A"' "$json_file")

    if [ "$pq_status" = "Yes" ] || [ "$pq_status" = "Hybrid" ]; then
      echo "- **$hostname** ($ip) - $pq_status" >> "$REPORT_DIR/compliance-report.md"
    fi
  fi
done

cat >> "$REPORT_DIR/compliance-report.md" <<EOF

### Quantum-Vulnerable Hosts (Classical Only)

EOF

# List classical-only hosts
for json_file in "$ANSIBLE_DIR/results"/*.json; do
  if [ -f "$json_file" ]; then
    hostname=$(basename "$json_file" | cut -d'-' -f1)
    pq_status=$(jq -r '.results[0].post_quantum_secure // "Unknown"' "$json_file")
    ip=$(jq -r '.results[0].target_ip // "N/A"' "$json_file")

    if [ "$pq_status" = "No" ]; then
      echo "- **$hostname** ($ip) - ⚠️ Classical crypto only" >> "$REPORT_DIR/compliance-report.md"
    fi
  fi
done

cat >> "$REPORT_DIR/compliance-report.md" <<EOF

## Recommendations

EOF

if [ $classical -gt 0 ]; then
  cat >> "$REPORT_DIR/compliance-report.md" <<EOF
1. **High Priority:** Upgrade $classical classical-only hosts to support post-quantum cryptography
2. Review harvest-now-decrypt-later (HNDL) exposure for sensitive workloads
3. Consider encryption gateways for devices that cannot be upgraded
EOF
else
  cat >> "$REPORT_DIR/compliance-report.md" <<EOF
✓ All scanned hosts support post-quantum or hybrid cryptography
✓ Continue monitoring for new deployments
✓ Maintain compliance through regular scans
EOF
fi

cat >> "$REPORT_DIR/compliance-report.md" <<EOF

## Detailed Results

See individual scan reports in:
\`$ANSIBLE_DIR/results/\`

---
*Generated by quantum-sniffer compliance check*
EOF

echo ""
echo "========================================"
echo "Compliance Check Complete"
echo "========================================"
echo ""
echo "Report saved to: $REPORT_DIR/compliance-report.md"
echo ""
cat "$REPORT_DIR/compliance-report.md"
